### ISSUE TITLE
gmail login option not showing up on browser

### ISSUE THREAD

**Issue by buni-gutz** [ApparyllisOrg/SimplyPluralApi#318]
im trying to login in to the web app (i already have an acc) but it is a gmail account and does not have a password set.

![image](https://github.com/user-attachments/assets/cd502c51-17f4-46a5-b1d3-3a85fcd6d0da)

i saw it just a few minutes before and after trying to login with the normal email-password signup, it disappeared. i am using opera gx, and have tried it on multiple profiles. its disappeared everywhere and now i am completely unable to get into my account

**Comment by Cellaryllis** [comment]
This is not an API issue, please only report API issues here. Furthermore this issue was resolved last week.

**Comment by Celestemysterios** [comment]
> This is not an API issue, please only report API issues here.

hi just made a issue about a bug in the app then saw this. where do you report bugs for the app?

**Comment by Cellaryllis** [comment]
> > This is not an API issue, please only report API issues here.
> 
> hi just made a issue about a bug in the app then saw this. where do you report bugs for the app?

Bugs for the app can be made in the Discord server. If you have no Discord, you can email us the bug.

**Comment by OrdinaryCloverOC** [comment]
> > > This is not an API issue, please only report API issues here.
> > 
> > 
> > hi just made a issue about a bug in the app then saw this. where do you report bugs for the app?
> 
> Bugs for the app can be made in the Discord server. If you have no Discord, you can email us the bug.

i have a limit on discord servers. respectfully i am not joining a discord to report bugs for a singular app.
